[package]
name = "r_delta"
version = "0.1.2"
edition = "2021"

[dependencies]
hex = "0.4"
clap = { version = "4.5.52", features = ["derive"] }
blake3 = "1.8.2"
zstd = "0.13"

[dev-dependencies]
tempfile = "3"

